# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0002_college_university_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='frontendapp.University'),
        ),
        migrations.AlterField(
            model_name='college',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
