# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0003_auto_20161020_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(default=None),
        ),
    ]
