# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0005_auto_20161020_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
