# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0006_auto_20161023_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='display_pic',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
