# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0007_college_display_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='display_pic',
        ),
    ]
