# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0008_auto_20161025_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='brief',
            field=models.CharField(default=b'We are working on the brief.', max_length=250),
        ),
    ]
