# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0010_auto_20161025_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='model_pic',
            field=models.ImageField(default=b'profile_pic/not_available.jpg', null=True, upload_to=b'profile_pic/college/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='model_pic',
            field=models.ImageField(default=b'profile_pic/not_available.jpg', null=True, upload_to=b'profile_pic/university/'),
        ),
    ]
