# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0011_auto_20161025_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
