# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0017_auto_20161118_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_College_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='frontendapp.College')),
                ('course', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='frontendapp.Courses')),
            ],
        ),
    ]
