# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0018_courses_college_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
