# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0019_auto_20161118_0720'),
        ('frontendapp', '0013_auto_20161026_0512'),
    ]

    operations = [
    ]
