# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0020_merge_20161118_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='model_pic_1',
            field=models.ImageField(default=b'profile_pic/not_available.jpg', null=True, upload_to=b'profile_pic/college/'),
        ),
        migrations.AddField(
            model_name='college',
            name='model_pic_2',
            field=models.ImageField(default=b'profile_pic/not_available.jpg', null=True, upload_to=b'profile_pic/college/'),
        ),
        migrations.AddField(
            model_name='college',
            name='model_pic_3',
            field=models.ImageField(default=b'profile_pic/not_available.jpg', null=True, upload_to=b'profile_pic/college/'),
        ),
    ]
