# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0022_college_placement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='activity_text',
            field=models.CharField(default=b'No data available. We are working towards bring you the information you requrie.', max_length=3000),
        ),
    ]
