# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0025_auto_20170121_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='placement_num_eligible1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_num_eligible2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_num_placed1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_num_placed2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_num_with_two_offers1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_num_with_two_offers2',
            field=models.IntegerField(default=0),
        ),
    ]
