# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0026_auto_20170121_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.ImageField(default=b'profile_pic/not_available.jpg', null=True, upload_to=b'profile_pic/college/'),
        ),
    ]
