# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0027_college_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='Placement_majorcompany1',
            new_name='placement_majorcompany1',
        ),
    ]
