# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0029_auto_20170122_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(default=b'not_available.jpg', null=True, upload_to=b'college/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='model_pic',
            field=models.ImageField(default=b'not_available.jpg', null=True, upload_to=b'college/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='model_pic_1',
            field=models.ImageField(default=b'not_available.jpg', null=True, upload_to=b'college/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='model_pic_2',
            field=models.ImageField(default=b'not_available.jpg', null=True, upload_to=b'college/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='model_pic_3',
            field=models.ImageField(default=b'not_available.jpg', null=True, upload_to=b'college/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='model_pic',
            field=models.ImageField(default=b'not_available.jpg', null=True, upload_to=b'university/'),
        ),
    ]
