# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontendapp', '0024_courses_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acs_date', models.DateTimeField(verbose_name=b'date created')),
                ('active', models.BooleanField(default=True)),
                ('hash_key', models.CharField(default=b'258f0916942882c315fb82d7967e1a', max_length=10, unique=True)),
                ('college', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='frontendapp.College')),
            ],
        ),
    ]
