# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'b7c9bae0c6aa923981e24ae35fb401', max_length=30, unique=True),
        ),
    ]
