# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0003_auto_20170120_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'50ad4ae23559890c8cc5426fc046cd', max_length=30, unique=True),
        ),
    ]
