# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0004_auto_20170120_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'3f4f427e88ffec186b879fd1e3a7cd', max_length=30, unique=True),
        ),
    ]
