# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0006_auto_20170120_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'87277b72b3ebe74c0234b0b99a89a9', max_length=30, unique=True),
        ),
    ]
