# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0008_auto_20170120_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'187f44289afbdbf4a61ad297bd3d86', max_length=30, unique=True),
        ),
    ]
