# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0009_auto_20170121_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'95f8657d164362916fb5c562bd344b', max_length=30, unique=True),
        ),
    ]
