# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0010_auto_20170121_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'232c09627612373b1b3210a2970a18', max_length=30, unique=True),
        ),
    ]
