# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0011_auto_20170121_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'f1234acdb809f62e97a2626c4bb854', max_length=30, unique=True),
        ),
    ]
