# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0012_auto_20170122_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'6d0f079f3ea49af4d13e098714fd52', max_length=30, unique=True),
        ),
    ]
