# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0014_auto_20170123_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'19dcf5b23c9d820796a41c8298a267', max_length=30, unique=True),
        ),
    ]
