# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwdsource', '0016_auto_20170125_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_ticket',
            name='hash_key',
            field=models.CharField(default=b'd2bdb04f0755041a457f9bebc35daf', max_length=30, unique=True),
        ),
    ]
